name: Deploy

on:
  push:
    branches:
      - 'master'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write #This is required for actions/checkout

    steps:
      - uses: actions/checkout@v4

      - name: Set up Java version
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'microsoft'

      - name: Setup Permissions
        run: chmod -c 777 gradlew

      - name: Run Tests
        run: ./gradlew test

      - name: Test Summary
        uses: test-summary/action@v2
        with:
          paths: "build/results/**/TEST-*.xml"
          output: test-summary.md
        if: always()

      - name: Upload test summary
        uses: actions/upload-artifact@v4
        with:
          name: test-summary
          path: test-summary.md
        if: always()

      - name: Build with Gradle
        run: ./gradlew build

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: fabric
          path: '${{ github.workspace }}/fabric/build/libs/*.jar'
      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: paper
          path: '${{ github.workspace }}/paper/build/libs/*.jar'
  deploy_packages:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
    permissions:
      id-token: write #This is required for requesting the JWT
      contents: read #This is required for actions/checkout

    steps:
      - uses: actions/checkout@v4

      - name: Set up Java version
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'microsoft'

      - name: Setup Permissions
        run: chmod -c 777 gradlew
      - name: Publish to Github Packages
        run: |
          ./gradlew publish
        env:
          GITHUB_ACTOR: ${{ github.actor }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PACKAGES_TOKEN: ${{ secrets.PACKAGES_TOKEN }}
          MODRINTH_TOKEN: ${{ secrets.MODRINTH_TOKEN }}
          DISCORD_CHANNEL: ${{ secrets.DISCORD_CHANNEL }}
          DISCORD_TOKEN: ${{ secrets.DISCORD_TOKEN }}
  deploy_modrinth:
    runs-on: ubuntu-latest
    needs: deploy_packages
    environment:
      name: 'Production'
    permissions:
      id-token: write #This is required for requesting the JWT
      contents: read #This is required for actions/checkout
    if: |
      github.event_name == 'workflow_dispatch' ||
      (github.ref == 'refs/heads/master')
    steps:
      - uses: actions/checkout@v4

      - name: Set up Java version
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'microsoft'

      - name: Setup Permissions
        run: chmod -c 777 gradlew
      - name: Publish to Modrinth
        run: |
          ./gradlew modrinth
        env:
          GITHUB_ACTOR: ${{ github.actor }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          MODRINTH_TOKEN: ${{ secrets.MODRINTH_TOKEN }}
          DISCORD_CHANNEL: ${{ secrets.DISCORD_CHANNEL }}
          DISCORD_TOKEN: ${{ secrets.DISCORD_TOKEN }}